### Тестирование экспорта заказов в 1С через CommerceML

### 1. Авторизация для экспорта заказов (sale/checkauth)
GET {{baseUrl}}/commerceml-proxy/?type=sale&mode=checkauth
Authorization: Basic MTIyNTcyNDc6ZGJmNjE0NThkYzM0MzE5ZWRhNDhhYzcxZjBlMTJlNjM=

### 2. Инициализация экспорта заказов (sale/init)
GET {{baseUrl}}/commerceml-proxy/?type=sale&mode=init
Cookie: COMMERCE1C_SESSION=commerce1c_690b17b1872468.40747510

### 3. Получение заказов для экспорта (sale/query)
GET {{baseUrl}}/commerceml-proxy/?type=sale&mode=query
Cookie: COMMERCE1C_SESSION=commerce1c_690b17b1872468.40747510

### 4. Подтверждение успешного импорта заказов в 1С (sale/success)
POST {{baseUrl}}/commerceml-proxy/?type=sale&mode=success
Cookie: COMMERCE1C_SESSION=commerce1c_690b17b1872468.40747510
Content-Type: application/json

{
  "order_ids": [1, 2, 3]
}

### 5. Подтверждение с XML данными
POST {{baseUrl}}/commerceml-proxy/?type=sale&mode=success
Cookie: COMMERCE1C_SESSION=commerce1c_690b17b1872468.40747510
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<КоммерческаяИнформация ВерсияСхемы="2.05">
  <Документы>
    <Документ>
      <Номер>1</Номер>
      <Статус>Импортирован</Статус>
    </Документ>
    <Документ>
      <Номер>2</Номер>
      <Статус>Импортирован</Статус>
    </Документ>
  </Документы>
</КоммерческаяИнформация>

### Переменные для тестирования
@baseUrl = https://xn----7sbnkf1eg0g.xn--p1ai
@sessionId = commerce1c_session_id_here

