### Тестирование интеграции с 1С через CommerceML (Cookie-авторизация)

# Настройки
@baseUrl = https://xn----7sbnkf1eg0g.xn--p1ai/commerceml-proxy
@username = 12257247
@password = dbf61458dc34319eda48ac71f0e12e63

### 1. Авторизация (checkauth) - получаем Cookie
GET {{baseUrl}}/?type=catalog&mode=checkauth
Authorization: Basic MTIyNTcyNDc6ZGJmNjE0NThkYzM0MzE5ZWRhNDhhYzcxZjBlMTJlNjM=

### 2. Инициализация (init) - используем Cookie из предыдущего ответа
GET {{baseUrl}}/?type=catalog&mode=init
Cookie: COMMERCE1C_SESSION=commerce1c_68fa85210b9807.99368436

### 3. Загрузка файла каталога (file) - используем Cookie
POST {{baseUrl}}/?type=catalog&mode=file&filename=import0_1.xml
Cookie: COMMERCE1C_SESSION=commerce1c_68fa85210b9807.99368436
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="UTF-8"?>
<КоммерческаяИнформация ВерсияСхемы="2.05" ДатаФормирования="2025-10-17T01:00:00">
    <Классификатор>
        <Ид>266538b7-f865-4666-8725-1f1a1f9c1267</Ид>
        <Наименование>Каталог товаров</Наименование>
        <Группы>
            <Группа>
                <Ид>group-1</Ид>
                <Наименование>Суши</Наименование>
                <Товары>
                    <Товар>
                        <Ид>product-1</Ид>
                        <Наименование>Филадельфия</Наименование>
                        <Артикул>SUSHI-001</Артикул>
                        <БазовыеЕдиницы Код="796" НаименованиеПолное="Штука" МеждународноеСокращение="PCE">шт</БазовыеЕдиницы>
                        <Группы>
                            <Ид>group-1</Ид>
                        </Группы>
                        <Описание>Классические суши Филадельфия с лососем и сливочным сыром</Описание>
                        <Картинка>sushi_philadelphia.jpg</Картинка>
                    </Товар>
                </Товары>
            </Группа>
            <Группа>
                <Ид>group-2</Ид>
                <Наименование>Роллы</Наименование>
                <Товары>
                    <Товар>
                        <Ид>product-2</Ид>
                        <Наименование>Калифорния</Наименование>
                        <Артикул>ROLL-001</Артикул>
                        <БазовыеЕдиницы Код="796" НаименованиеПолное="Штука" МеждународноеСокращение="PCE">шт</БазовыеЕдиницы>
                        <Группы>
                            <Ид>group-2</Ид>
                        </Группы>
                        <Описание>Роллы Калифорния с крабом и авокадо</Описание>
                        <Картинка>roll_california.jpg</Картинка>
                    </Товар>
                </Товары>
            </Группа>
        </Группы>
    </Классификатор>
</КоммерческаяИнформация>

### 4. Импорт каталога (import) - используем Cookie
GET {{baseUrl}}/?type=catalog&mode=import&filename=import0_1.xml
Cookie: COMMERCE1C_SESSION=commerce1c_68fa7ee6dd0ce1.30862458

### 5. Загрузка файла предложений (file) - используем Cookie
POST {{baseUrl}}/?type=catalog&mode=file&filename=offers0_1.xml
Cookie: COMMERCE1C_SESSION=commerce1c_68fa664c435276.16138303
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="UTF-8"?>
<КоммерческаяИнформация ВерсияСхемы="2.05" ДатаФормирования="2025-10-17T01:00:00">
    <ПакетПредложений>
        <Ид>266538b7-f865-4666-8725-1f1a1f9c1267</Ид>
        <Наименование>Предложения</Наименование>
        <ТипыЦен>
            <ТипЦены>
                <Ид>price-type-1</Ид>
                <Наименование>Розничная</Наименование>
                <Валюта>RUB</Валюта>
            </ТипЦены>
        </ТипыЦен>
        <Предложения>
            <Предложение>
                <Ид>product-1</Ид>
                <Наименование>Филадельфия</Наименование>
                <Количество>50</Количество>
                <Цены>
                    <Цена>
                        <ИдТипаЦены>price-type-1</ИдТипаЦены>
                        <ЦенаЗаЕдиницу>450.00</ЦенаЗаЕдиницу>
                        <Валюта>RUB</Валюта>
                    </Цена>
                </Цены>
            </Предложение>
            <Предложение>
                <Ид>product-2</Ид>
                <Наименование>Калифорния</Наименование>
                <Количество>30</Количество>
                <Цены>
                    <Цена>
                        <ИдТипаЦены>price-type-1</ИдТипаЦены>
                        <ЦенаЗаЕдиницу>380.00</ЦенаЗаЕдиницу>
                        <Валюта>RUB</Валюта>
                    </Цена>
                </Цены>
            </Предложение>
        </Предложения>
    </ПакетПредложений>
</КоммерческаяИнформация>

### 6. Импорт предложений (import) - используем Cookie
GET {{baseUrl}}/?type=catalog&mode=import&filename=offers0_1.xml
Cookie: COMMERCE1C_SESSION=commerce1c_68fa8144b41bc2.75000730
